config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("control.urls")),
    path("sponsors/",include("sponsors.urls")),
    path("accounts/",include("django.contrib.auth.urls")),

    re_path(r"media/(.*)", serve, {"document_root": settings.MEDIA_ROOT}),
]

control/urls.py
from django.urls import path

from control.views import HomePage, sendMessagePage, taskStatusApi

app_name = "adm"

urlpatterns = [
    path("", HomePage.as_view(), name="home"),
    path("task/<int:pk>/", taskStatusApi.as_view(), name="task"),
    path("send/message/", sendMessagePage.as_view(), name="send-message"),
]

sponsors/urls.py
from django.urls import path

from sponsors.views import HomePage, DeletePage, CreatePage, UpdatePage

app_name = "sponsors"

urlpatterns = [
    path("list/", HomePage.as_view(), name="list"),
    path("delete/<int:pk>/", DeletePage.as_view(), name="delete"),
    path("create/", CreatePage.as_view(), name="create"),
    path("edit/<int:pk>/", UpdatePage.as_view(), name="edit"),
]

bot/models.py
from django.db import models


class User(models.Model):
    user_id = models.BigIntegerField(unique=True)

    def __str__(self) -> str:
        return str(self.user_id)


class Videos(models.Model):
    file_id = models.CharField(max_length=255)
    url = models.CharField(max_length=255)
    video_id = models.CharField(max_length=255, blank=True, null=True)

control/models.py
from django.db import models


class Tasks(models.Model):
    total = models.IntegerField(default=0)
    done = models.IntegerField(default=0)
    error = models.IntegerField(default=0)
    success = models.BooleanField(default=False)

    def __str__(self):
        return str("{}|{}|{}".format(self.total, self.done, self.error))

sponsors/models.py
from django.db import models


class Sponsors(models.Model):
    link = models.CharField(max_length=255)
    name = models.CharField(max_length=1000)
    pic = models.ImageField(upload_to='chanels_pics/', default="chanels_pics/default.png")
    username = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self) -> str:
        return self.name

control/forms.py
from django import forms
from django.forms import widgets


class sendMessageForm(forms.Form):
    file = forms.FileField(required=False)
    message = forms.CharField()
    keyboards = forms.CharField(label="Tugmalar", required=False, widget=widgets.Textarea())

bot/views.py
from django.shortcuts import render

# Create your views here.

control/views.py
import io
import mimetypes
from threading import Thread

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from rest_framework.generics import get_object_or_404
from rest_framework.response import Response
from rest_framework.views import APIView

from bot.models import User
from control.forms import sendMessageForm
from control.models import Tasks
from control.tasks import sendMessageTask
from sponsors.models import Sponsors


# fayil turini olish uchun
def get_file_mime_type(file):
    file_name = file.name
    mime_type, _ = mimetypes.guess_type(file_name)
    mime_type = mime_type.split("/")[0]
    return mime_type


class HomePage(LoginRequiredMixin,View):

    def get(self, request):
        context = {
            "users": User.objects.all().count(),
            "sponsors": Sponsors.objects.all().count(),
            "tasks": Tasks.objects.order_by("id").reverse().all()
        }

        return render(request, "dashboard.html", context=context)


class sendMessagePage(LoginRequiredMixin,View):

    def get(self, request):
        form = sendMessageForm()
        context = {
            "form": form
        }

        return render(request, "control/send-message.html", context)

    def post(self, request):
        global kbs
        form = sendMessageForm(data=request.POST)

        context = {
            "form": form
        }

        if not form.is_valid():
            return render(request, "control/send-message.html", context)

        file = request.FILES.get("file", None)

        message = form.data.get("message")

        mime_type = "text"
        try:
            mime_type = get_file_mime_type(file)
        except Exception as e:
            print(e)

        keyboards = form.data.get("keyboards", None)
        if keyboards is not None:
            validator = URLValidator()
            keyboards = str(keyboards).replace("\r", "").split("\n")
            kbs = []
            for keyboard in keyboards:
                keyboard = keyboard.split("=")
                if len(keyboard) != 2:
                    continue

                url = keyboard[1].replace(" ", "")
                try:
                    validator(url)
                except ValidationError as e:
                    form.add_error("keyboards", "Tugma nato'g'ri formatda kiritildi")
                    return render(request, "control/send-message.html", context)

                kbs.append({"title": keyboard[0], "url": url})

        if len(kbs) == 0:
            kbs = None
        if kbs is None and (keyboards is not None and "" != str(keyboards[0]).replace(" ", "")):
            form.add_error("keyboards", "Tugma nato'g'ri formatda kiritildi")
            return render(request, "control/send-message.html", context)

        bio = None

        if file is not None:
            content = file.read()

            bio = io.BytesIO(content)

        task = Tasks()
        task.save()

        task = Thread(target=sendMessageTask,
                      kwargs={'type': mime_type, "keyboards": kbs, "file": bio, "message": message, "task": task.id})
        task.start()

        messages.success(request, "Foydalanuvchilarga xabar yuborish boshlandi")
        return redirect(reverse("adm:home"))


class taskStatusApi(APIView):
    def get(self, request, pk):
        task = get_object_or_404(Tasks, id=pk)
        context = {
            "task": task.id,
            "total": task.total,
            "done": task.done,
            "error": task.error,
            "success": task.success,
        }
        return Response(context)

sponsors/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, UpdateView, DeleteView, CreateView

from bot.management.commands.loader import bot
from sponsors.models import Sponsors


class HomePage(LoginRequiredMixin, ListView):
    template_name = "sponsors/list.html"
    model = Sponsors


class UpdatePage(LoginRequiredMixin, UpdateView):
    template_name = "sponsors/edit.html"
    model = Sponsors
    fields = "__all__"
    success_url = reverse_lazy("sponsors:list")


class DeletePage(LoginRequiredMixin, DeleteView):
    template_name = "sponsors/delete.html"
    model = Sponsors
    success_url = reverse_lazy("sponsors:list")


class CreatePage(LoginRequiredMixin, CreateView):
    template_name = "sponsors/create.html"
    model = Sponsors
    fields = ['link']
    success_url = reverse_lazy("sponsors:list")

    def form_valid(self, form):
        link = self.request.POST.get("link")

        try:
            chat = bot.get_chat(link)
            name = chat.title
            username = chat.username
            me = bot.get_me()
            form.instance.name = name
            form.instance.username = username

            check = bot.get_chat_member(chat.id, me.id)

            if check.status != "administrator":
                messages.error(self.request, "Bot kanalda admin emas")
                return redirect(reverse("sponsors:create"))



        except Exception as e:
            print(e)
            messages.error(self.request,
                           "Kanal topilmadi yoki nato'g'ri formatda kiritdingiz example: @channel_user_name agarda bu ishlamasa kanal id raqamini yuboring")
            return redirect(reverse("sponsors:create"))

        form.save()

        return redirect(reverse("sponsors:list"))

templates/components/footer.html
{% load static %}

<div class="footer_part default_footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="footer_iner text-center">
                    <p>2023 © TBT Group <a href="#"> <i class="ti-heart"></i> </a><a href="https://t.me/TBTGroupIT">Telegram</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/sidebar.html
{% load static %}
<nav class="sidebar vertical-scroll  ps-container ps-theme-default ps-active-y">
    <div class="logo d-flex justify-content-between">
        <a href="{% url "adm:home" %}"><img src="{% static "img/logo-2.png" %}" alt></a>
        <div class="sidebar_close_icon d-lg-none">
            <i class="ti-close"></i>
        </div>
    </div>
    <ul id="sidebar_menu">
        <li class="mm-active">
            <a class="" href="{% url "adm:home" %}" aria-expanded="false">
                <div class="icon_menu">
                    <img src="{% static "img/menu-icon/dashboard.svg" %}" alt>
                </div>
                <span>Bosh sahifa</span>
            </a>
        </li>
        <li class="mm-active">
            <a class="" href="{% url "sponsors:list" %}" aria-expanded="false">
                <div class="icon_menu">
                    <img src="{% static "img/menu-icon/dashboard.svg" %}" alt>
                </div>
                <span>Homiylar</span>
            </a>
        </li>
        <li class="mm-active">
            <a class="" href="{% url "adm:send-message" %}" aria-expanded="false">
                <div class="icon_menu">
                    <img src="{% static "img/menu-icon/dashboard.svg" %}" alt>
                </div>
                <span>Xabar yuborish</span>
            </a>
        </li>
    </ul>
</nav>

templates/control/send-message.html
{% extends "layouts/main.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <div class="white_card card_height_100 mb_30">
        <div class="white_card_header">
            <div class="box_header m-0">
                <div class="main-title">
                    <h3 class="m-0">Foydalanuvchilarga xabar yuborish</h3>
                </div>
            </div>
        </div>
        <div class="white_card_body">
            <div class="row d-flex justify-content-center">
                <div class="col-12 col-sm-8 col-md-7 col-lg-6 col-xl-6">
                    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                        {{ form|crispy }}
                        <div class="footer d-flex justify-content-end">
                            <button class="btn btn-success">Yuborish</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/dashboard.html
{% extends "layouts/main.html" %}
{% load utils %}
{% block content %}
    <style>
        .box-shadow {
            box-shadow: 0px 10px 22px 11px rgba(0, 0, 0, 0.1);
        }
    </style>
    <div class="row">
        <div class="col-lg-12">
            <div class="single_element">
                <div class="quick_activity">
                    <div class="row">
                        <div class="col-12">
                            <div class="row gap-3 justify-content-center">
                                <div class="single_quick_activity col-12 col-sm-5 col-xl-5">
                                    <div class="count_content">
                                        <p>Foydalanuvchilar</p>
                                        <h3><span class="counter">{{ users }}</span></h3>
                                    </div>
                                    <a href="#" class="notification_btn">Jami</a>
                                    <div id="bar1" class="barfiller">
                                        <div class="tipWrap">
                                            <span class="tip"></span>
                                        </div>
                                        <span class="fill" data-percentage="100"></span>
                                    </div>
                                </div>
                                <div class="single_quick_activity col-12 col-sm-5 col-xl-5">
                                    <div class="count_content">
                                        <p>Homiylar</p>
                                        <h3><span class="counter">{{ sponsors }}</span></h3>
                                    </div>
                                    <a href="#" class="notification_btn violate_btn">Jami</a>
                                    <div id="bar4" class="barfiller">
                                        <div class="tipWrap">
                                            <span class="tip"></span>
                                        </div>
                                        <span class="fill" data-percentage="100"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 mt-4 mb-3">
                            <h1>Tasklar</h1>
                            {% for task in tasks|slice:"5" %}
                                <div class="quick_activity_wrap bg-white box-shadow p-4 rounded-3">
                                    <div style="height: 100px" class="single_quick_activity bg-warning">
                                        <div class="count_content">
                                            <p class="text-white">Jami</p>
                                            <h3><span class="counter text-white"
                                                      id="total-{{ task.id }}">{{ task.total }}</span></h3>
                                        </div>
                                    </div>
                                    <div style="height: 100px" class="single_quick_activity bg-primary">
                                        <div class="count_content">
                                            <p class="text-white">Yuborildi</p>
                                            <h3><span class="counter text-white"
                                                      id="done-{{ task.id }}">{{ task.done }}</span></h3>
                                        </div>
                                    </div>
                                    <div style="height: 100px" class="single_quick_activity bg-danger">
                                        <div class="count_content">
                                            <p class="text-white">Xatolik</p>
                                            <h3><span class="counter text-white"
                                                      id="error-{{ task.id }}">{{ task.error }}</span></h3>
                                        </div>
                                    </div>
                                    <div style="height: 100px" class="single_quick_activity bg-success">
                                        <div class="count_content">
                                            <p class="text-white">Status</p>
                                            <h4><span class="text-white"
                                                      id="success-{{ task.id }}">{% if task.success %}
                                                Bajarildi{% else %}Bajarilmoqda{% endif %}</span>
                                            </h4>
                                        </div>
                                    </div>
                                </div>
                                <script>
                                    if ("{{ task.success }}" === "False") {
                                        let interval{{ task.id }} = setInterval(() => {
                                            fetch("{% url "adm:task" pk=task.id %}").then(res => {
                                                return res.json()
                                            }).then(res => {
                                                document.querySelector("#total-{{ task.id }}").innerText = res.total
                                                document.querySelector("#done-{{ task.id }}").innerText = res.done
                                                document.querySelector("#error-{{ task.id }}").innerText = res.error

                                                if (res.success === true) {
                                                    document.querySelector("#success-{{ task.id }}").innerText = "Bajarildi"
                                                    clearInterval(interval{{ task.id }})
                                                }

                                            }).catch(res => {
                                                console.log(res)
                                            })
                                        }, 1000)
                                    }
                                </script>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/layouts/main.html
{% load static %}
{% load utils %}
<!DOCTYPE html>
<html lang="zxx">

<!-- Mirrored from demo.dashboardpack.com/marketing-html/index_2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 22 Jul 2023 13:54:33 GMT -->
<head>

    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <title>Marketing</title>
    <link rel="icon" href="{% static "img/logo.png" %}" type="image/png">
    <link rel="stylesheet" href="{% static "css/bootstrap1.min.css" %}"/>
    <link rel="stylesheet" href="{% static "vendors/themefy_icon/themify-icons.css" %}"/>
    <link rel="stylesheet" href="{% static "vendors/niceselect/css/nice-select.css" %}"/>
    <link rel="stylesheet" href="{% static "vendors/owl_carousel/css/owl.carousel.css" %}"/>
    <link rel="stylesheet" href="{% static "vendors/gijgo/gijgo.min.css" %}"/>
    <link rel="stylesheet" href="{% static "vendors/font_awesome/css/all.min.css" %}"/>
    <link rel="stylesheet" href="{% static "vendors/tagsinput/tagsinput.css" %}"/>
    <link rel="stylesheet" href="{% static "vendors/datepicker/date-picker.css" %}"/>
    <link rel="stylesheet" href="{% static "vendors/scroll/scrollable.css" %}"/>
    <link rel="stylesheet" href="{% static "vendors/datatable/css/jquery.dataTables.min.css" %}"/>
    <link rel="stylesheet" href="{% static "vendors/datatable/css/responsive.dataTables.min.css" %}"/>
    <link rel="stylesheet" href="{% static "vendors/datatable/css/buttons.dataTables.min.css" %}"/>
    <link rel="stylesheet" href="{% static "vendors/text_editor/summernote-bs4.css" %}"/>
    <link rel="stylesheet" href="{% static "vendors/morris/morris.cs" %}s">
    <link rel="stylesheet" href="{% static "vendors/material_icon/material-icons.css" %}"/>
    <link rel="stylesheet" href="{% static "css/metisMenu.cs" %}s">
    <link rel="stylesheet" href="{% static "css/style1.css" %}"/>
    <link rel="stylesheet" href="{% static "css/colors/default.css" %}" id="colorSkinCS">
</head>
<body class="crm_body_bg">


{% include "components/sidebar.html" %}


<section class="main_content dashboard_part default_content">

    <div class="container-fluid g-0">
        <div class="row">
            <div class="col-lg-12 p-0 ">
                <div class="header_iner d-flex justify-content-between align-items-center">
                    <div class="sidebar_icon d-lg-none">
                        <i class="ti-menu" style="color: black"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="main_content_iner">

        <div class="container-fluid p-0">
            {% for message in messages %}
                <div class="alert text-white bg-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} d-flex align-items-center justify-content-between"
                     role="alert">
                    <div class="alert-text">{{ message }}</div>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
            {% block content %}
            {% endblock content %}
        </div>
    </div>

    {% include "components/footer.html" %}
</section>

<script src="{% static "js/jquery1-3.4.1.min.js" %}"></script>
<script src="{% static "js/popper1.min.js" %}"></script>
<script src="{% static "js/bootstrap1.min.js" %}"></script>
<script src="{% static "js/metisMenu.js" %}"></script>
<script src="{% static "vendors/count_up/jquery.waypoints.min.js" %}"></script>
<script src="{% static "vendors/chartlist/Chart.min.js" %}"></script>
<script src="{% static "vendors/count_up/jquery.counterup.min.js" %}"></script>
<script src="{% static "vendors/niceselect/js/jquery.nice-select.min.js" %}"></script>
<script src="{% static "vendors/owl_carousel/js/owl.carousel.min.js" %}"></script>
<script src="{% static "vendors/datatable/js/jquery.dataTables.min.js" %}"></script>
<script src="{% static "vendors/datatable/js/dataTables.responsive.min.js" %}"></script>
<script src="{% static "vendors/datatable/js/dataTables.buttons.min.js" %}"></script>
<script src="{% static "vendors/datatable/js/buttons.flash.min.js" %}"></script>
<script src="{% static "vendors/datatable/js/jszip.min.js" %}"></script>
<script src="{% static "vendors/datatable/js/pdfmake.min.js" %}"></script>
<script src="{% static "vendors/datatable/js/vfs_fonts.js" %}"></script>
<script src="{% static "vendors/datatable/js/buttons.html5.min.js" %}"></script>
<script src="{% static "vendors/datatable/js/buttons.print.min.js" %}"></script>
<script src="{% static "js/chart.min.js" %}"></script>
<script src="{% static "vendors/progressbar/jquery.barfiller.js" %}"></script>
<script src="{% static "vendors/tagsinput/tagsinput.js" %}"></script>
<script src="{% static "vendors/text_editor/summernote-bs4.js" %}"></script>
<script src="{% static "vendors/am_chart/amcharts.js" %}"></script>
<script src="{% static "vendors/apex_chart/apexcharts.js" %}"></script>
<script src="{% static "vendors/apex_chart/apex_dashboard.js" %}"></script>
<script src="{% static "vendors/scroll/perfect-scrollbar.min.js" %}"></script>
<script src="{% static "vendors/scroll/scrollable-custom.js" %}"></script>
<script src="{% static "vendors/chart_am/core.js" %}"></script>
<script src="{% static "vendors/chart_am/charts.js" %}"></script>
<script src="{% static "vendors/chart_am/animated.js" %}"></script>
<script src="{% static "vendors/chart_am/kelly.js" %}"></script>
<script src="{% static "vendors/chart_am/chart-custom.js" %}"></script>

<script src="{% static "js/custom.js" %}"></script>
</body>

<!-- Mirrored from demo.dashboardpack.com/marketing-html/index_2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 22 Jul 2023 13:54:34 GMT -->
</html>

templates/sponsors/create.html
{% extends "layouts/main.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <div class="white_card card_height_100 mb_30">
        <div class="white_card_header">
            <div class="box_header m-0">
                <div class="main-title">
                    <h3 class="m-0">Homiy qo'shish</h3>
                </div>
            </div>
        </div>
        <div class="white_card_body">
            <div class="row d-flex justify-content-center">
                <div class="col-12 col-sm-8 col-md-7 col-lg-6 col-xl-6">
                    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                        {{ form|crispy }}
                        <div class="footer d-flex justify-content-end">
                            <button class="btn btn-success">Saqlash</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/sponsors/delete.html
{% extends "layouts/main.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <div class="white_card card_height_100 mb_30">
        <div class="white_card_header">
            <div class="box_header m-0">
                <div class="main-title">
                    <h3 class="m-0">Homiy o'chirish</h3>
                </div>
            </div>
        </div>
        <div class="white_card_body">
            <div class="row d-flex justify-content-center">
                <div>
                    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                        <h4>Title: {{ object.name }}</h4>
                        <h4>Link: {{ object.link }}</h4>
                        <div class="footer mt-5 d-flex justify-content-end">
                            <a href="{% url "sponsors:list" %}" class="btn btn-success me-5">Yo'q</a>
                            <button class="btn btn-danger">ha</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/sponsors/edit.html
{% extends "layouts/main.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <div class="white_card card_height_100 mb_30">
        <div class="white_card_header">
            <div class="box_header m-0">
                <div class="main-title">
                    <h3 class="m-0">Homiy qo'shish</h3>
                </div>
            </div>
        </div>
        <div class="white_card_body">
            <div class="row d-flex justify-content-center">
                <div class="col-12 col-sm-8 col-md-7 col-lg-6 col-xl-6">
                    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                        {{ form|crispy }}
                        <div class="footer d-flex justify-content-end">
                            <button class="btn btn-success">Saqlash</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/sponsors/list.html
{% extends "layouts/main.html" %}

{% block content %}

    <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="white_card card_height_100 mb_30">
                <div class="white_card_header">
                    <div class="box_header m-0">
                        <div class="d-flex justify-content-between w-100">
                            <h3 class="m-0">Homiylar</h3>
                            <a href="{% url "sponsors:create" %}" class="btn btn-primary">Qo'shish</a>
                        </div>
                    </div>
                </div>
                <div class="white_card_body">
                    <div class="QA_section">

                        <div class="QA_table mb_30">

                            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper no-footer">
                                <table class="table dataTable no-footer dtr-inline"
                                       id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info"
                                       style="width: 1061px;">
                                    <thead>
                                    <tr role="row">
                                        <th scope="col" class="sorting_asc" tabindex="0"
                                            aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                                            style="width: 121px;" aria-sort="ascending"
                                            aria-label="title: activate to sort column descending">Image
                                        </th>
                                        <th scope="col" class="sorting" tabindex="0" aria-controls="DataTables_Table_0"
                                            rowspan="1" colspan="1" style="width: 147px;"
                                            aria-label="Category: activate to sort column ascending">Title
                                        </th>
                                        <th scope="col" class="sorting" tabindex="0" aria-controls="DataTables_Table_0"
                                            rowspan="1" colspan="1" style="width: 152px;"
                                            aria-label="Teacher: activate to sort column ascending">Link
                                        </th>
                                        <th scope="col" class="sorting" tabindex="0" aria-controls="DataTables_Table_0"
                                            rowspan="1" colspan="1" style="width: 152px;"
                                            aria-label="Teacher: activate to sort column ascending">#
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for sponsor in sponsors_list %}
                                        <tr role="row" class="odd">
                                            <th scope="row" tabindex="0" class="sorting_1"><img
                                                    src="{{ sponsor.pic.url }}"
                                                    alt="rasim topilmadi" style="width: 50px">
                                            </th>
                                            <td>{{ sponsor.name }}</td>
                                            <td>{{ sponsor.link }}</td>
                                            <td>
                                                <a href="{% url "sponsors:delete" pk=sponsor.id %}"
                                                   class="btn btn-danger btn-sm text-white">
                                                    <i class="fas fa-trash"></i>
                                                </a>
{#                                                <a href="{% url "sponsors:edit" pk=sponsor.id %}"#}
{#                                                   class="btn btn-primary btn-sm">#}
{#                                                    <i class="fas fa-edit text-white"></i>#}
{#                                                </a>#}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12">
        </div>
    </div>
{% endblock content %}